/**
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { endGroup, startGroup } from "@actions/core";
import type { GitHub } from "@actions/github/lib/utils";
import { Context } from "@actions/github/lib/context";
import {
  ChannelSuccessResult,
  interpretChannelDeployResult,
  ErrorResult,
} from "./deploy";
import { createDeploySignature } from "./hash";
import { getInput } from "@actions/core";
import { context } from "@actions/github";
import { getOctokit } from "@actions/github";

const showDetailedUrls = getInput("showDetailedUrls") === "true";
const token = process.env.GITHUB_TOKEN || getInput("repoToken");
const octokit = getOctokit(token);
const pullRequest = context.payload.pull_request;
const pullRequestNumber = pullRequest.number;

// 新增：异步函数以获取 PR 中的文件列表
async function getChangedFilesList(pullRequestNumber: number): Promise<string[]> {
  const response = await octokit.rest.pulls.listFiles({
    owner: context.repo.owner,
    repo: context.repo.repo,
    pull_number: pullRequestNumber,
  });
  return response.data.map(file => file.filename);
}

const BOT_SIGNATURE = "Generated by your GitHub Action";

export function createBotCommentIdentifier(signature: string) {
  return function isCommentByBot(comment): boolean {
    return comment.user.type === "Bot" && comment.body.includes(signature);
  };
}

export function getURLsMarkdownFromChannelDeployResult(
  result: ChannelSuccessResult
): string {
  const { urls } = interpretChannelDeployResult(result);

  return urls.length === 1
    ? `[${urls[0]}](${urls[0]})`
    : urls.map((url) => `- [${url}](${url})`).join("\n");
}

export function getChannelDeploySuccessComment(
  result: ChannelSuccessResult,
  commit: string
) {
  const deploySignature = createDeploySignature(result);
  const urlList = getURLsMarkdownFromChannelDeployResult(result);
  const { expireTime } = interpretChannelDeployResult(result);

  return `
Visit the preview URL for this PR (updated for commit ${commit}):

${urlList}

<sub>(expires ${new Date(expireTime).toUTCString()})</sub>

${BOT_SIGNATURE}

<sub>Sign: ${deploySignature}</sub>`.trim();
}

export async function postChannelSuccessComment(
  github: InstanceType<typeof GitHub>,
  context: Context,
  result: ChannelSuccessResult,
  commit: string
) {
  const commentInfo = {
    ...context.repo,
    issue_number: context.issue.number,
  };

  const commentMarkdown = getChannelDeploySuccessComment(result, commit);

  const comment = {
    ...commentInfo,
    body: commentMarkdown,
  };

  startGroup(`Commenting on PR`);
  const deploySignature = createDeploySignature(result);
  const isCommentByBot = createBotCommentIdentifier(deploySignature);

  let commentId;
  try {
    const comments = (await github.rest.issues.listComments(commentInfo)).data;
    for (let i = comments.length; i--; ) {
      const c = comments[i];
      if (isCommentByBot(c)) {
        commentId = c.id;
        break;
      }
    }
  } catch (e) {
    console.log("Error checking for previous comments: " + e.message);
  }

  if (commentId) {
    try {
      await github.rest.issues.updateComment({
        ...context.repo,
        comment_id: commentId,
        body: comment.body,
      });
    } catch (e) {
      commentId = null;
    }
  }

  if (!commentId) {
    try {
      await github.rest.issues.createComment(comment);
    } catch (e) {
      console.log(`Error creating comment: ${e.message}`);
    }
  }
  endGroup();
}

export async function postPRFilesComment(
  github: InstanceType<typeof GitHub>,
  context: Context,
  fileList: string[] // 接收文件列表参数
) {
  const fileListMarkdown = fileList.map(file => `- ${file}`).join('\n');
  
  const commentMarkdown = `
### Files Changed in this PR:
${fileListMarkdown}

${BOT_SIGNATURE}`;

  // 这里是将评论发布到 PR 的逻辑
  const commentInfo = {
    ...context.repo,
    issue_number: context.issue.number,
    body: commentMarkdown
  };

  startGroup(`Commenting on PR`);
  const isCommentByBot = createBotCommentIdentifier(BOT_SIGNATURE);

  let commentId;
  try {
    const comments = (await github.rest.issues.listComments(commentInfo)).data;
    for (let i = comments.length; i--; ) {
      const c = comments[i];
      if (isCommentByBot(c)) {
        commentId = c.id;
        break;
      }
    }
  } catch (e) {
    console.log("Error checking for previous comments: " + e.message);
  }

  if (commentId) {
    try {
      await github.rest.issues.updateComment({
        ...context.repo,
        comment_id: commentId,
        body: commentMarkdown,
      });
    } catch (e) {
      commentId = null;
    }
  }

  if (!commentId) {
    try {
      await github.rest.issues.createComment(commentInfo);
    } catch (e) {
      console.log(`Error creating comment: ${e.message}`);
    }
  }
  endGroup();
}

// 新增：调用函数以获取文件列表并发表评论
(async () => {
  if (context.eventName === 'pull_request') {
    const fileList = await getChangedFilesList(pullRequestNumber);
    await postPRFilesComment(octokit, context, fileList);
  }
})();